- name: Stop & MASK Nginx
  systemd:
    name: nginx
    state: stopped
    enabled: no
    masked: yes

- name: Ensure Apache + mod_wsgi + WeasyPrint OS deps
  apt:
    name:
      - apache2
      - libapache2-mod-wsgi-py3
      - libcairo2
      - libpango-1.0-0
      - libpangoft2-1.0-0
      - libpangocairo-1.0-0
      - libgdk-pixbuf2.0-0
      - shared-mime-info
      - fonts-dejavu-core
      - libffi-dev
      - python3-venv
      - python3-pip
      - build-essential
      - python3-dev
      - libssl-dev
      - libpq-dev
    state: present
    update_cache: yes

- name: Enable Apache modules
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  loop: [ 'wsgi','headers','rewrite' ]

- name: Set Apache global ServerName
  copy:
    dest: /etc/apache2/conf-available/servername.conf
    content: "ServerName {{ (domains | default(['localhost']))[0] }}\n"
    mode: '0644'

- name: Enable servername.conf
  file:
    src: /etc/apache2/conf-available/servername.conf
    dest: /etc/apache2/conf-enabled/servername.conf
    state: link
    force: true

- name: Create project directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/openwisp2
    - /opt/openwisp2/static
    - /opt/openwisp2/media
    - /opt/openwisp2/private

- name: Create venv
  command: python3 -m venv /opt/openwisp2/env
  args: { creates: /opt/openwisp2/env/bin/activate }

- name: Upgrade pip in venv
  pip:
    name: pip
    state: latest
    executable: /opt/openwisp2/env/bin/pip

- name: Install Python deps in venv
  pip:
    name:
      - "django==4.2.*"
      - django-allauth
      - dj-rest-auth
      - openwisp-users
      - openwisp-radius
      - django-private-storage
      - weasyprint
    executable: /opt/openwisp2/env/bin/pip

- name: Generate Django secret (once)
  shell: "python3 - << 'PY'\nimport secrets, pathlib\np=pathlib.Path('/opt/openwisp2/.django-secret-key')\nprint('exists' if p.exists() else p.write_text(secrets.token_urlsafe(64)))\nPY"
  args: { creates: /opt/openwisp2/.django-secret-key }

- name: Start Django project if missing
  command: /opt/openwisp2/env/bin/python -m django startproject openwisp2 .
  args: { chdir: /opt/openwisp2, creates: /opt/openwisp2/manage.py }

- name: Deploy settings.py
  template:
    src: settings.py.j2
    dest: /opt/openwisp2/openwisp2/settings.py
    mode: '0644'

- name: Deploy Apache vhost (HTTP only)
  template:
    src: apache_openwisp.conf.j2
    dest: /etc/apache2/sites-available/openwisp.conf
    mode: '0644'

- name: Disable default site
  file: { path: /etc/apache2/sites-enabled/000-default.conf, state: absent }

- name: Enable openwisp site
  file:
    src: /etc/apache2/sites-available/openwisp.conf
    dest: /etc/apache2/sites-enabled/openwisp.conf
    state: link
    force: true

- name: Migrate DB (SQLite)
  command: /opt/openwisp2/env/bin/python manage.py migrate --noinput
  args: { chdir: /opt/openwisp2 }
  register: mig
  changed_when: "'No migrations to apply' not in (mig.stdout | default(''))"

- name: Collect static
  command: /opt/openwisp2/env/bin/python manage.py collectstatic --noinput
  args: { chdir: /opt/openwisp2 }
  changed_when: true

- name: Restart Apache
  service: { name: apache2, state: restarted, enabled: yes }
