- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    name: "{{ base_packages }}"
    state: present

- name: Ensure IP forwarding enabled
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

# 1) پیش از فعال‌سازی UFW، قوانین لازم را اضافه کن (جلوگیری از قفل شدن SSH)
- name: Allow TCP ports (pre-enable)
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ (firewall_allow_tcp | default([22])) | unique }}"

- name: Allow UDP ports (pre-enable)
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  loop: "{{ firewall_allow_udp | default([]) }}"

# 2) سیاست‌ها را ست کن
- name: Set default incoming policy to deny
  community.general.ufw:
    direction: incoming
    policy: deny

# 3) فعال‌سازی نهایی
- name: Enable UFW
  community.general.ufw:
    state: enabled
